import { Link, useNavigate, useParams } from 'react-router-dom'
import { buildMatchSummary } from '../lib/engine'
import { deleteMatch, getMatch } from '../lib/storage'
import { formatDate, formatDuration } from '../lib/utils'
import type { Player, PlayerAnalysis, PlayerStats } from '../types'

function Compare({ label, home, away, suffix = '' }: { label: string; home: number; away: number; suffix?: string }) {
  const total = Math.max(1, home + away)
  return <section className="panel comparison"><div className="comparison-heading"><span>{label}</span><span className="comparison-label">双方对比</span></div><div className="dual-numbers"><span className="home">{home}{suffix}</span><span className="away">{away}{suffix}</span></div><div className="metric-track" aria-label={`${label}：我方 ${home}${suffix}，对方 ${away}${suffix}`}><i className="home" style={{ width: `${home / total * 100}%` }} /><i className="away" style={{ width: `${away / total * 100}%` }} /></div><div className="metric-ticks" aria-hidden /></section>
}

function PlayerCard({ player, analysis }: { player: Player; analysis: PlayerAnalysis }) {
  const s = analysis.stats
  return <article className="panel player-card"><header className="player-head"><div><div className="player-name"><span className="player-number">{player.number}</span>{player.name}</div><span className="position">{player.position}</span></div><div className="player-score"><b>{analysis.score.toFixed(1)}</b><span>演示评分 / 10</span></div></header><p className="mt-3 text-xs text-[var(--text-muted)]">演示数据 · 真实分析待接入</p><div className="data-list"><span>拿球 <b>{s.touches}</b></span><span>传球 <b>{s.passesSuccess}/{s.passes}</b></span><span>传球失误 <b>{Math.max(0, s.passes - s.passesSuccess)}</b></span><span>被断球 <b>{s.dispossessed}</b></span><span>射门 <b>{s.shotsOnTarget}/{s.shots}</b></span><span>突破 <b>{s.dribbles}</b></span><span>拦截 <b>{s.interceptions}</b></span><span>抢断 <b>{s.tackles}</b></span><span>其他失误 <b>{s.turnovers}</b></span></div>{analysis.insights.slice(0, 2).map((insight) => <p className="insight" key={insight}>{insight}</p>)}</article>
}

function TeamStats({ analyses }: { analyses: PlayerAnalysis[] }) { const total = (key: keyof PlayerStats) => analyses.reduce((sum, item) => sum + item.stats[key], 0); return <section className="mt-8"><h2 className="section-title mb-3">全队数据 <span className="text-xs font-normal text-[var(--text-muted)]">· 演示数据</span></h2><div className="team-stats"><div className="team-stat"><b>{total('touches')}</b><span>总拿球</span></div><div className="team-stat"><b>{total('passes')}</b><span>总传球</span></div><div className="team-stat"><b>{total('shots')}</b><span>总射门</span></div><div className="team-stat"><b>{total('turnovers') + total('dispossessed')}</b><span>总失误</span></div></div></section> }

export default function MatchReport() {
  const { id } = useParams(); const navigate = useNavigate(); const match = id ? getMatch(id) : undefined
  if (!match) return <div className="page-shell px-4 py-24 text-center"><p className="text-[var(--text-secondary)]">未找到该比赛</p><Link to="/" className="btn-primary mt-6">返回首页</Link></div>
  if (!match.analysis) { navigate(`/match/${match.id}/analyzing`, { replace: true }); return null }
  const analyses = match.analysis; const shots = analyses.reduce((sum, item) => sum + item.stats.shots, 0); const average = analyses.length ? analyses.reduce((sum, item) => sum + item.score, 0) / analyses.length : 0; const summary = buildMatchSummary(match, analyses); const map = new Map(match.players.map((player) => [player.id, player])); const rows = analyses.map((analysis) => ({ analysis, player: map.get(analysis.playerId) })).filter((row): row is { analysis: PlayerAnalysis; player: Player } => Boolean(row.player))
  return <div className="report-page"><div className="report-shell"><header className="flex items-center justify-between gap-3"><div><Link to="/" className="text-sm text-[var(--text-muted)]">← 首页</Link><p className="report-meta mt-2">{formatDate(match.date)} · {match.name} · {match.type} · {formatDuration(match.duration)}</p></div><span className="text-xs text-[var(--text-muted)]">演示数据</span></header><p className="mt-6 text-lg font-medium leading-7 text-[var(--text-primary)]">{summary.headline}</p><section className="score-hero"><div className="grid min-w-0 flex-1 grid-cols-[minmax(0,1fr)_auto_auto_auto_minmax(0,1fr)] items-center gap-3 sm:gap-4"><span className="score-team home">{match.teamName}</span><span className="score-number home">{match.myScore}</span><span className="score-dash">—</span><span className="score-number away">{match.oppScore}</span><span className="score-team away">{match.opponentName}</span></div><aside className="team-average"><span>球队平均分</span><b>{average.toFixed(1)}</b></aside></section><div className="report-divider" /><div className="comparison-grid mt-3"><Compare label="控球率" home={match.possessionHome ?? 50} away={match.possessionAway ?? 50} suffix="%" /><Compare label="射门" home={shots} away={match.shotsAway ?? 0} /></div><section className="summary-grid"><article className="summary-item highlight"><h2>球队亮点 · 演示数据</h2><p>{summary.headline}</p></article><article className="summary-item weakness"><h2>球队不足 · 演示数据</h2><p>{summary.points[0] ?? '继续减少失误，让每次处理更从容'}</p></article><article className="summary-item focus"><h2>下一步关注 · 演示数据</h2><p>{summary.points[1] ?? '继续观察传球、射门和防守数据'}</p></article></section><details className="mt-8"><summary className="section-title cursor-pointer">查看球员概览 <span className="text-xs font-normal text-[var(--text-muted)]">· 演示数据</span></summary><div className="mt-4 player-grid">{rows.map(({ player, analysis }) => <PlayerCard key={player.id} player={player} analysis={analysis} />)}</div></details><TeamStats analyses={analyses} /><div className="mt-8 flex justify-end"><button className="btn-secondary !border-[var(--danger)] !text-[var(--danger)]" onClick={() => { if (window.confirm('确定删除这场比赛及其看板吗？')) { deleteMatch(match.id); navigate('/', { replace: true }) } }}>删除</button></div></div></div>
}
