import { Link, useNavigate, useParams } from 'react-router-dom'
import { getMatch } from '../lib/storage'

function formatBytes(value?: number) { if (!value) return '演示片段'; if (value < 1024 * 1024) return `${Math.ceil(value / 1024)} KB`; return `${(value / 1024 / 1024).toFixed(1)} MB` }
function formatDuration(value?: number) { if (!value || !Number.isFinite(value)) return '未读取'; return `${Math.floor(value / 60)}:${Math.round(value % 60).toString().padStart(2, '0')}` }

export default function VideoQuality() {
  const { id } = useParams(); const navigate = useNavigate(); const match = id ? getMatch(id) : undefined
  if (!match) return <div className="page-shell grid place-items-center px-4"><section className="panel max-w-md p-6 text-center"><p className="text-[var(--text-secondary)]">找不到这段视频记录。</p><Link className="btn-primary mt-5" to="/match/new">重新选择视频</Link></section></div>
  const meta = match.videoMeta
  return <div className="page-shell px-4 py-10"><div className="mx-auto max-w-2xl"><header className="mb-7"><p className="eyebrow">画面检查 · 本地演示</p><h1 className="mt-2 text-3xl font-semibold text-[var(--text-primary)]">看一眼拍摄条件，再开始分析</h1><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">这里只读取视频基础信息，不上传文件；下一步将使用演示数据，真实分析待接入。</p></header><section className="panel p-5 sm:p-6"><div className="flex items-start gap-3 border-b border-[var(--line)] pb-5"><span className="upload-icon !m-0 shrink-0" aria-hidden>✓</span><div className="min-w-0"><p className="truncate font-medium text-[var(--text-primary)]">{match.videoName}</p><p className="mt-1 text-xs text-[var(--text-muted)]">本地文件 · {formatBytes(meta?.sizeBytes)}</p></div></div><dl className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-md border border-[var(--line)] bg-[var(--line)] sm:grid-cols-3"><div className="bg-[var(--content)] p-4"><dt className="text-xs text-[var(--text-muted)]">时长</dt><dd className="mt-2 font-score text-xl text-[var(--text-primary)]">{formatDuration(meta?.durationSeconds)}</dd></div><div className="bg-[var(--content)] p-4"><dt className="text-xs text-[var(--text-muted)]">画幅</dt><dd className="mt-2 font-score text-xl text-[var(--text-primary)]">{meta?.width && meta?.height ? `${meta.width}×${meta.height}` : '未读取'}</dd></div><div className="bg-[var(--content)] p-4"><dt className="text-xs text-[var(--text-muted)]">状态</dt><dd className="mt-2 text-sm text-[var(--ai)]">演示可继续</dd></div></dl><div className="mt-6 rounded-md border border-[var(--line)] bg-[var(--content)] p-4"><p className="text-sm font-medium text-[var(--text-primary)]">拍摄建议</p><p className="mt-3 text-sm leading-6 text-[var(--text-secondary)]">横屏、固定、覆盖主区域、保持明亮；低机位、过暗或严重抖动时，仅适合基础回看，建议重拍。</p></div><div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Link className="btn-secondary" to="/match/new">换一段视频</Link><button className="btn-primary" onClick={() => navigate(`/match/${match.id}/analyzing`)}>开始本地演示分析 <span aria-hidden>→</span></button></div></section></div></div>
}
